[package]
name = "gen-meter"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
domain = { path = "../../domain" }
csv = { workspace = true }
